version: "2.2"
# Remain on v2 for https://github.com/docker/compose/issues/4513

volumes:
  gerbera-kinder-cds:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/gerberaKinderCDs
      o: bind

  gerbera-kinder-filme:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/gerberaKinderFilme
      o: bind

  gerbera-musik:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/gerberaMusik
      o: bind

  kinder-cds:
    driver: local
    driver_opts:
      type: none
      device: /share/KinderCDs
      o: bind

  kinder-filme:
    driver: local
    driver_opts:
      type: none
      device: /share/KinderFilme
      o: bind

  musik:
    driver: local
    driver_opts:
      type: none
      device: /share/Musik
      o: bind

  portainer:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/portainer
      o: bind

#networks:
#   backend:
#     driver: bridge

services:
# Note: 'network_mode: host' is required for the upnp server for multicast traffic
#       to detect the upnp server.
  gerbera-kinder-filme:
    restart: unless-stopped
    build:
      context: gerbera
    network_mode: host
    environment:
      - CONFIG=49155-kinder-filme
    volumes:
      - kinder-filme:/media:nocopy
      - gerbera-kinder-filme:/gerbera_home

  gerbera-kinder-cds:
    restart: unless-stopped
    build:
      context: gerbera
    network_mode: host
    environment:
      - CONFIG=49156-kinder-cds
    volumes:
      - kinder-cds:/media:nocopy
      - gerbera-kinder-cds:/gerbera_home

  gerbera-musik:
    restart: unless-stopped
    build:
      context: gerbera
    network_mode: host
    environment:
      - CONFIG=49154-musik
    volumes:
      - musik:/media:nocopy
      - gerbera-musik:/gerbera_home

  portainer:
    restart: unless-stopped
    image: portainer/portainer
    ports:
      - 8008:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data:nocopy
