version: "2.2"
# Remain on v2 for https://github.com/docker/compose/issues/4513

volumes:
  gerbera-kinder-cds:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/gerberaKinderCDs
      o: bind

  gerbera-kinder-filme:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/gerberaKinderFilme
      o: bind

  gerbera-musik:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/gerberaMusik
      o: bind

  kinder-cds:
    driver: local
    driver_opts:
      type: none
      device: /share/KinderCDs
      o: bind

  kinder-filme:
    driver: local
    driver_opts:
      type: none
      device: /share/KinderFilme
      o: bind

  musik:
    driver: local
    driver_opts:
      type: none
      device: /share/Musik
      o: bind

#   portainer:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=192.168.6.22,nolock,rw
#       device: :/nfs/Data/linux/portainer-strom
#
#   pi-hole_etc_pihole:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=192.168.6.22,nolock,rw
#       device: :/nfs/Data/linux/pi-hole/etc_pihole
#
#   pi-hole_etc_dnsmasq.d:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=192.168.6.22,nolock,rw
#       device: :/nfs/Data/linux/pi-hole/etc_dnsmasq.d

networks:
  backend:
    driver: bridge

services:
# Note: 'network_mode: host' is required for the upnp server for multicast traffic
#       to detect the upnp server.
  gerbera-kinder-filme:
    restart: unless-stopped
    build:
      context: gerbera
    network_mode: host
    environment:
      - CONFIG=49152-kinder-filme
    volumes:
      - kinder-filme:/media:nocopy
      - gerbera-kinder-filme:/gerbera_home

  gerbera-kinder-cds:
    restart: unless-stopped
    build:
      context: gerbera
    network_mode: host
    environment:
      - CONFIG=49153-kinder-cds
    volumes:
      - kinder-cds:/media:nocopy
      - gerbera-kinder-cds:/gerbera_home

  gerbera-musik:
    restart: unless-stopped
    build:
      context: gerbera
    network_mode: host
    environment:
      - CONFIG=49154-musik
    volumes:
      - musik:/media:nocopy
      - gerbera-musik:/gerbera_home

#   pi-hole:
#     restart: unless-stopped
#     build: pi-hole
# #    image: diginc/pi-hole-multiarch:debian_armhf
#     ports:
#       - 53:53/tcp
#       - 53:53/udp
#       - 80:80
#       - 443:443
#     environment:
#       - ServerIP=192.168.6.6
#       - WEBPASSWORD=1234
#     volumes:
#       - pi-hole_etc_pihole:/etc/pihole:nocopy
#       - pi-hole_etc_dnsmasq.d:/etc/dnsmasq.d:nocopy
# 
#   portainer:
#     restart: unless-stopped
#     image: portainer/portainer
#     ports:
#       - 8008:9000
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - portainer:/data:nocopy
# 
#   strom:
#     restart: unless-stopped
#     build:
#       context: strom
#       args:
#         - CACHE_DATE=2018-04-18
#     ports:
#       - 9083:9083
#     cap_add:
#       - SYS_RAWIO
#     devices:
#       - /dev/ttyAMA0:/dev/ttyAMA0
#     networks:
#       - backend
#     volumes:
#       - strom:/var/strom:nocopy
# #    links:
# #      - postfix
# #      - pigpiod
# 
#   stubby:
#     restart: unless-stopped
#     build:
#       context: stubby
#       args:
#         - CACHE_DATE=2018-07-15
#     ports:
# #     - 127.0.0.1:53:53/tcp
# #     - 127.0.0.1:53:53/udp
#      - 6653:6653/tcp
#      - 6653:6653/udp
#     networks:
#       - backend
