version: "2.2"
# Remain on v2 for https://github.com/docker/compose/issues/4513

volumes:
  gerbera-kinder-cds:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/gerberaKinderCDs
      o: bind

  gerbera-kinder-filme:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/gerberaKinderFilme
      o: bind

  gerbera-musik:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/gerberaMusik
      o: bind

  kinder-cds:
    driver: local
    driver_opts:
      type: none
      device: /share/KinderCDs
      o: bind

  kinder-filme:
    driver: local
    driver_opts:
      type: none
      device: /share/KinderFilme
      o: bind

  musik:
    driver: local
    driver_opts:
      type: none
      device: /share/Musik
      o: bind

  portainer:
    driver: local
    driver_opts:
      type: none
      device: /share/linux/data/portainer
      o: bind

#  pihole_etc_pihole:
#    driver: local
#    driver_opts:
#      type: none
#      device: /share/linux/pihole/etc_pihole
#      o: bind

#  pihole_etc_dnsmasq.d:
#    driver: local
#    driver_opts:
#      type: none
#      device: /share/linux/pihole/etc_dnsmasq.d
#      o: bind

# networks:
#   bridge:
#     driver: bridge
#  qnet-static:
#    driver: qnet
#    ipam:
#      driver: qnet
#      options:
#        iface: "eth0"
#      config:
#      - subnet: 192.168.6.1/24
#        gateway: 192.168.6.1
#
#   backend:
#     driver: bridge
#  vpcbr:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 192.168.6.0/24
#          gateway: 192.168.6.1

services:
# Note: 'network_mode: host' is required for the upnp server for multicast traffic
#       to detect the upnp server.
  gerbera-kinder-filme:
    restart: unless-stopped
    build:
      context: gerbera
    network_mode: host
    environment:
      - CONFIG=49155-kinder-filme
    volumes:
      - kinder-filme:/media:nocopy
      - gerbera-kinder-filme:/gerbera_home

  gerbera-kinder-cds:
    restart: unless-stopped
    build:
      context: gerbera
    network_mode: host
    environment:
      - CONFIG=49156-kinder-cds
    volumes:
      - kinder-cds:/media:nocopy
      - gerbera-kinder-cds:/gerbera_home

  gerbera-musik:
    restart: unless-stopped
    build:
      context: gerbera
    network_mode: host
    environment:
      - CONFIG=49154-musik
    volumes:
      - musik:/media:nocopy
      - gerbera-musik:/gerbera_home

#  pihole:
#    restart: unless-stopped
#    image: pihole/pihole
#    networks:
#      qnet-static:
#        ipv4_address: 192.168.6.8
#    mac_address: 02:42:9B:32:46:48
#    ports:
#      - 53:53/tcp
#      - 53:53/udp
#      - 80:80
#      - 443:443
#    environment:
#      - ServerIP=192.168.6.8
#      - WEBPASSWORD=1234
#      - IPv6=False
#      - TZ=Europe/Berlin
#      - DNS1="1.1.1.1"
#      - DNS2="1.0.0.1"
#    volumes:
#      - pihole_etc_pihole:/etc/pihole:nocopy
#      - pihole_etc_dnsmasq.d:/etc/dnsmasq.d:nocopy

  portainer:
    restart: unless-stopped
    image: portainer/portainer
#    networks:
#      - bridge
    ports:
      - 8008:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data:nocopy
