#!/bin/bash

# shellcheck disable=SC2155

export ESC="\\033"
export CTLG="\\007"
export HEADER="$ESC]2;"
BOLDRED="${ESC}[1;31m"
BGGREEN="${ESC}[48;5;2m${ESC}[38;5;7m"
INVERSE="${ESC}[7m"
FAILEDX='\342\234\227'
NORMAL="${ESC}[0m"

###############################################################################
# Prompt

HOSTNAME=$(hostname)

set_ps1() {
  LAST_RESULT=$? # Must come first!

  PS1=""

  # If the last command failed, print a red X.
  if [ $LAST_RESULT != 0 ]; then
    PS1+="\[$BOLDRED\]$FAILEDX($LAST_RESULT)\[$NORMAL\] "
  fi

  PS1+="\[$BGGREEN\]${HOSTNAME}\[$NORMAL\] \[$INVERSE\]"'${PWD#$HOME/}'"\[$NORMAL\] # "
}
PROMPT_COMMAND='set_ps1'

###############################################################################
# Functions for konsole and xterm title
start_vi() {
  for PARAM in "$@"; do
    if [ -z "$START_VI_DISPLAY_TITLE" ]; then
      if [[ "$PARAM" != -* ]]; then
        START_VI_DISPLAY_TITLE=$(basename "$PARAM" |
          sed -e 's/^include\.//' \
              -e 's/\.js$//' \
              -e 's/\.jsx$//' \
              -e 's/\.php$//' \
              -e 's/\.p[ml]$//' \
              -e 's/^.phptime.log$/time/'
        )

        echo -e "${HEADER}${START_VI_DISPLAY_TITLE}${CTLG}\c"
      fi
    fi
  done

  unset START_VI_DISPLAY_TITLE

  nice -15 "$EDITOR" "$@"

  echo -e "${HEADER}${TITLE_PREFIX}${TITLE}${CTLG}\c"
}

export EDITOR=vim
alias vi=start_vi

###############################################################################
# Console label

TITLE_PREFIX=
TITLE_PREFIX=${HOSTNAME}
echo -e "${HEADER}${TITLE_PREFIX}${TITLE}${CTLG}\c"

###############################################################################
# Alias etc..
alias ll='ls -l'
set -o vi
export PATH=/share/linux/tools/busybox/:/share/CACHEDEV1_DATA/.qpkg/Entware/bin/:$PATH:/share/CACHEDEV1_DATA/.qpkg/container-station/bin/

alias dcps="docker compose ps --format 'table {{.ID}}\t{{.Service}}\t{{.Status}}\t{{.Ports}}'"
alias dsdf="docker system df --verbose --format '{{range .Containers}}{{.Size}}\t{{.Names}}\n{{end}}' | sort -h"
alias dcl="docker compose logs --tail 100 -f"

# Load nvm
NVM_DIR="$(realpath "$HOME/.nvm")"
export NVM_DIR
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
