volumes:
  wecker:
    driver: local
    driver_opts:
      type: none
      device: /mnt/qnap_linux/data/wecker
      o: bind

services:
  noop:
    restart: always
    build: noop
    hostname: wyse-noop

  watchdog:
    restart: always
    build: watchdog
    hostname: pi-wecker-watchdog
    volumes:
      - ./watchdog/app:/app
    ports:
      - 31038:31038

  wecker:
    restart: always
    build:
      context: wecker
    hostname: raspi-wecker
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/input:/dev/input
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
      - /dev/snd:/dev/snd
    volumes:
      - /dev/input/by-path:/dev/input/by-path
      - wecker:/var/wecker
      - ./wecker/app:/app
