version: "3.2"

volumes:
  portainer:
    driver: local
    driver_opts:
      type: none
      device: /docker-data/portainer
      o: bind

  postfix_creds:
    driver: local
    driver_opts:
      type: none
      device: /mnt/qnap_linux/data/postfix_creds
      o: bind

  wecker:
    driver: local
    driver_opts:
      type: none
      device: /docker-data/wecker
      o: bind

networks:
  backend:
    driver: bridge

services:
  portainer:
    restart: unless-stopped
    image: portainer/portainer-ce
    ports:
      - 8008:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data:nocopy

  postfix:
    restart: always
    build: postfix
    hostname: pi-postfix
    ports:
      - "25:25"
    networks:
      - backend
    volumes:
      - postfix_creds:/postfix_creds:nocopy

  watchdog:
    restart: always
    build: watchdog
    hostname: pi-wecker-watchdog
    volumes:
      - ./watchdog/app:/app
    networks:
      - backend
    ports:
      - 31038:31038
    links:
      - postfix

  wecker:
    restart: always
    build:
      context: wecker
    hostname: raspi-wecker
    networks:
      - backend
    cap_add:
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/input:/dev/input
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
      - /dev/snd:/dev/snd

    volumes:
      - /dev/input/by-path:/dev/input/by-path
      - wecker:/var/wecker
      - ./wecker/app:/app
