FROM b4tman/squid:latest

# ##############################################################################
# Base environment

# RUN sudo apk add --no-cache  \
#     bash

ENV TZ Europe/Berlin

COPY docker_container_profile /var/cache/squid/.profile
