version: "3.2"

volumes:
  portainer:
    driver: local
    driver_opts:
      type: none
      device: /docker-data/portainer
      o: bind

  strom:
    driver: local
    driver_opts:
      type: none
      device: /mnt/qnap_linux/data/strom
      o: bind

networks:
  backend:
    driver: bridge

services:
  portainer:
    restart: always
    image: portainer/portainer
    ports:
      - 8008:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data:nocopy

  strom:
    restart: always
    build:
      context: strom
      args:
        - CACHE_DATE=2018-04-18
    hostname: strom-strom
    ports:
      - 9083:9083
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    networks:
      - backend
    volumes:
      - ./strom/app:/app
      - strom:/var/strom

  watchdog:
    restart: "no"
    build: watchdog
    hostname: pi-jalousie-watchdog
    volumes:
      - ./watchdog/app:/app
    networks:
      - backend
    ports:
      - 31038:31038
#    links:
#      - postfix
